name: Mini CI/CD sans code

on: [push]

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Fake test (CI)
      run: echo "Tests OK"

    - name: Fake build (CI)
      run: echo "Build OK"

    - name: Fake deploy (CD)
      run: |
        mkdir deploy
        echo "Deployed locally" > deploy/status.txt
